
name: J2LINT

on:
  push:
    branches: [ github-actions ]
    #paths: "**.j2"
  pull_request:
    branches: [ github-actions ]
     
  workflow_dispatch:

jobs:
  J2LINT:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup J2Lint
        run: |
          git clone https://github.com/aristanetworks/j2lint.git
          python3 -m venv myenv
          source myenv/bin/activate
          sudo apt-get install python3-pip
          pip3 install jinja2      
          
      - name: Run J2lint
        #continue-on-error: true
        run: |
          source myenv/bin/activate
          cd j2lint
          python setup.py install
          j2lint $GITHUB_WORKSPACE 
